### ISSUE TITLE
Стили

### ISSUE THREAD

**Issue by coursar** [zulfat95/Homework-Cashback#1]
https://github.com/zulfat95/Homework-Cashback/blob/3d99c01b5dfaa4ea2088d1121cdc35ab07004a26/src/style.css#L1-L3

1. Стили обычно кладут в каталог css
2. Чтобы они прогружались, на них нужно ссылаться в index.html
3. После этого не забыть добавить в travis.yml, чтобы они развёртывались на Github Pages

**Comment by zulfat95** [comment]
1. Добавил в каталог css.
2. `<link rel="stylesheet" type="text/css" href="css/style.css">` ссылка есть.
3. `- cp -R src/index.html src/js src/css/style.css dist`.
Как только не прописывал в тревисе - при сборке у меня не прогружает мои стили, а буусттрап - прогружает. В консоли браузера - "Failed to load resource: the server responded with a status of 404 ()", в sources мой файл пустой.

**Comment by coursar** [comment]
Нужно было прописать src/css. Теперь вам нужно сдлеать git pull.
