### ISSUE TITLE
Не передавайте данные в массиве (ваши данные - разнородны), лучше сделайте три параметра у функции

### ISSUE THREAD

**Issue by coursar** [zulfat95/Homework-Cashback#3]
https://github.com/zulfat95/Homework-Cashback/blob/3d99c01b5dfaa4ea2088d1121cdc35ab07004a26/src/js/cb.js#L3

Тогда будет ошибиться сложнее.

**Comment by zulfat95** [comment]
Добавил параметры, теперь работает при вводе пустого значения 👍

**Comment by coursar** [comment]
Если сделали - надо закрывать issue
